services:
  apache:
    build: ./apache
    container_name: apache_server
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    volumes:
      - ./html:/var/www/html
      - ./logs/apache:/var/log/apache2
    networks:
      - appnet

  php:
    build: ./php
    container_name: php_fpm_v2
    expose:
      - "9000"
    volumes:
      - ./html:/var/www/html
      - ./logs/php:/var/log/php
    networks:
      - appnet
    healthcheck:
      test: ["CMD", "php", "-v"]
      interval: 30s
      timeout: 5s
      retries: 3

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: richardp
      POSTGRES_PASSWORD: Password1!
      POSTGRES_DB: postgresdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@localhost.com
      PGADMIN_DEFAULT_PASSWORD: Password1!
    ports:
      - "8082:80"
    depends_on:
      - postgres
    networks:
      - appnet

networks:
  appnet:
    driver: bridge

volumes:
  pgdata:
