ServerName localhost

<VirtualHost *:80>
    ServerName localhost
    #Redirect permanent / https://localhost/
</VirtualHost>

DocumentRoot "/var/www/html"

<Directory "/var/www/html">
    AllowOverride All
    Options +FollowSymLinks -Indexes
    Require all granted
</Directory>

DirectoryIndex index.php index.html

TypesConfig conf/mime.types

ErrorLog /var/log/apache2/error.log
CustomLog /var/log/apache2/access.log combined

<FilesMatch "\.php$">
    SetHandler "proxy:fcgi://php_fpm_v2:9000"
</FilesMatch>

<IfModule mod_php7.c>
    php_flag engine off
</IfModule>
<IfModule mod_php8.c>
    php_flag engine off
</IfModule>

ServerTokens Prod
ServerSignature Off

KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 5
